/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.invoiceagent;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc; import java.util.regex.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc class InvoiceAgentApiIntegrationTests {
 @Autowired MockMvc mvc; private String operatorToken; private String plannerToken;
 @BeforeEach void login()throws Exception{operatorToken=token("operator","Demo@2026");plannerToken=token("planner","Demo@2026");}
 private String token(String u,String p)throws Exception{String json=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+u+"\",\"password\":\""+p+"\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();Matcher matcher=Pattern.compile("\\\"token\\\":\\\"([^\\\"]+)\\\"").matcher(json);if(!matcher.find())throw new AssertionError("登录响应中缺少 token");return matcher.group(1);}
 @Test void operatorCanReadWorkspace()throws Exception{mvc.perform(get("/api/shopfloor/dashboard").header("Authorization","Bearer "+operatorToken)).andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true)).andExpect(jsonPath("$.data.metrics[0].label").value("今日发票批次"));}
 @Test void plannerCanReadQueue()throws Exception{mvc.perform(get("/api/admin/work-orders").header("Authorization","Bearer "+plannerToken)).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(3));}
 @Test void operatorCanRunPreview()throws Exception{mvc.perform(post("/api/shopfloor/agent-preview").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"objective\":\"核验进项发票和四单匹配\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.runtime").value("invoice-audit-demo")).andExpect(jsonPath("$.data.steps.length()").value(3));}
 @Test void operatorCanUseDomainGuard()throws Exception{mvc.perform(post("/api/shopfloor/invoice-audit").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"invoiceCode\":\"INV-913527\",\"amount\":26800.00,\"contractMatched\":true,\"duplicateRisk\":false,\"taxRuleMatched\":true,\"financeApproved\":false}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.route").value("CHECK_PASSED")).andExpect(jsonPath("$.data.riskScore").value(0));}
 @Test void operatorCanReleaseControlledPayment()throws Exception{mvc.perform(post("/api/enterprise/invoice/payment-release").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"invoiceCode\":\"INV-100\",\"vendorId\":\"V-100\",\"amount\":26800,\"dueDate\":\"2026-09-20\",\"asOfDate\":\"2026-09-11\",\"invoiceAuthentic\":true,\"threeWayMatchPassed\":true,\"duplicateRisk\":false,\"vendorActive\":true,\"taxRuleMatched\":true,\"sanctionsScreenPassed\":true,\"bankAccountChanged\":false,\"bankChangeVerified\":true,\"disputeOrHoldActive\":false,\"budgetAvailable\":true,\"requesterId\":\"requester-a\",\"approverIds\":[\"approver-a\",\"approver-b\"],\"requiredApprovals\":2}"))
  .andExpect(status().isOk()).andExpect(jsonPath("$.data.decision").value("RELEASE"))
  .andExpect(jsonPath("$.data.paymentFingerprint").isNotEmpty());}
 @Test void anonymousRequestIsDenied()throws Exception{mvc.perform(get("/api/admin/dashboard")).andExpect(status().isForbidden());}
}
